// svelte/src/components/CreateTodo.svelte
<script>
    export let todos;
    export let creatingTodo;

    const createTodo = (e) => {
        todos = [...todos, { task: e.target[0].value, completed: false }];
        e.target[0].value = "";
    };
</script>

<div class="card">
    <div class="card-content">
        <form class="form" on:submit|preventDefault={createTodo}>
            <label for="todo" class="label">Nova tarefa</label>
            <div class="field expanded-field">
                <input
                    name="todo"
                    class="input"
                    type="text"
                    placeholder="Tarefa"
                    autocomplete="off"
                />
            </div>
            <div class="field actions-left">
                <button
                    type="button"
                    class="btn btn-danger"
                    on:click={() => creatingTodo = false}
                >
                    Cancelar
                </button>
                <button type="submit" class="btn btn-primary">Criar</button>
            </div>
        </form>
    </div>
</div>

// vue/src/components/CreateTodo.vue
<script>
export default {
    props: {
        creatingTodo: {
            type: Boolean,
            required: true
        },
        todos: {
            type: Array,
            required: true
        }
    },
    methods: {
        createTodo() {
            this.todos.push({
                task: this.newTask,
                completed: false
            });

            this.disableCreateTodo();
        },
        disableCreateTodo() {
            this.$emit('disableCreateTodo');
        }
    },
    data() {
        return {
            newTask: ''
        }
    }
}
</script>

<template>
    <div class="card">
        <div class="card-content">
            <form class="form" @submit.prevent="createTodo">
                <label for="todo" class="label">Nova tarefa</label>
                <div class="field expanded-field">
                    <input name="todo" class="input" type="text" placeholder="Tarefa" autocomplete="off" v-model="newTask">
                </div>
                <div class="field actions-left">
                    <button type="button" class="btn btn-danger" @click="disableCreateTodo">
                        Cancelar
                    </button>
                    <button type="submit" class="btn btn-primary">Criar</button>
                </div>
            </form>
        </div>
    </div>
</template>
