// react/src/App.jsx
import Todo from './components/Todo'

import { useState } from 'react'

export const App = () => {
  const [todos, setCount] = useState([
    {
      task: "Fazer apps com Vue",
      completed: false,
    },
    {
      task: "Programar JavaScript",
      completed: false
    },
  ])

  return (
    <>
      <h1 className="title">TODO React</h1>
      <div className="content">
        {todos.map((todo, i) => (
          <Todo key={i} todo={{ ...todo, id: i }} />
        ))}
        <button className="btn btn-primary btn-create-todo">
          Criar tarefa
        </button>
      </div>
    </>
  )
}

export default App

// vue/src/App.vue
<script>
import Todo from "./components/Todo.vue";
import CreateTodo from "./components/CreateTodo.vue";

export default {
  data() {
    return {
      todos: [
        {
          task: "Fazer apps com Vue",
          completed: false,
        },
        {
          task: "Programar JavaScript",
          completed: false
        },
      ],
      creatingTodo: false
    };
  },
  components: {
    Todo,
    CreateTodo
  },
  methods: {
    deleteTodo(id) {
      this.todos.splice(id, 1);
    },
    disableCreateTodo() {
      this.creatingTodo = false;
    }
  }
};
</script>

<template>
  <h1 class="title">TODO Vue</h1>

  <div class="content">
    <div class="card" v-for="(todo, i) in todos" :key="i">
      <Todo :todo="{ ...todo, id: i }" @deleteTodo="deleteTodo" />
    </div>
    <CreateTodo v-if="creatingTodo" :creatingTodo="creatingTodo" v-bind="{ todos }" @disableCreateTodo="disableCreateTodo" />
    <button class="btn btn-primary btn-create-todo" @click="creatingTodo = true" v-else>
      Criar tarefa
    </button>
  </div>
</template>
