// vue/src/components/Todo.vue
<script>
export default {
    props: {
        todo: {
            type: Object,
            required: true
        }
    },
    methods: {
        deleteTodo() {
            this.$emit('deleteTodo', this.todo.id);
        },
        completeTodo() {
            this.todo.completed = !this.todo.completed;
        }
    },
    emits: ['deleteTodo']
}
</script>

<template>
    <input type="checkbox" @click="completeTodo">
    <div class="card-content">
        <p :class="{ completed: todo.completed }">{{ todo.task }}</p>
    </div>
    <button class="btn btn-danger" @click="deleteTodo">
        Delete
    </button>
</template>

// svelte/src/components/Todo.svelte
<script>
    import { createEventDispatcher } from "svelte";

    export let todo;

    const dispatch = createEventDispatcher();

    const completeTodo = () => {
        todo.completed = !todo.completed;
    }

    const deleteTodo = () => {
        dispatch("deleteTodo", todo.id);
    }
</script>

<div class="card">
    <input 
        type="checkbox"
        on:click={completeTodo}
    >
    <div class="card-content">
        <p class={todo.completed ? "completed" : ""}>
            {todo.task}
        </p>
    </div>
    <button
        class="btn btn-danger"
        on:click={deleteTodo}
    >
        Delete
    </button>
</div>
