// react/src/components/Todo.jsx
import React from 'react'

const Todo = ({ todo }) => {
    return (
        <div className="card">
            <input type="checkbox" />
            <div className="card-content">
                {todo.task}
            </div>
            <button className="btn btn-danger">
                Delete
            </button>
        </div>
    )
}

export default Todo

// svelte/src/components/Todo.svelte
<script>
    export let todo;

    const completeTodo = () => {
        todo.completed = !todo.completed
    }
</script>

<div class="card">
    <input 
        type="checkbox"
        on:click={completeTodo}
    >
    <div class="card-content">
        <p class={todo.completed ? "completed" : ""}>
            {todo.task}
        </p>
    </div>
    <button class="btn">
        Delete
    </button>
</div>
